const express = require('express');
const { translateText } = require('../utils/bhashini');
const Notification = require('../models/Notification');
const User = require('../models/user');
const apiResponse = require('../utils/apiResponse');
const logger = require('../utils/logger');

const router = express.Router();

/**
 * POST /api/notifications
 * When a High-Risk alert is generated by AI or system:
 * 1. Checks user's preferred language ('en', 'hi', 'as', 'bn').
 * 2. Calls await translateText(alertMessage, 'en', userLang) via Bhashini API.
 * 3. Saves to MongoDB and sends/dispatches translated payload (SMS/Socket).
 */
router.post('/', async (req, res) => {
  try {
    const { userId, message, type = 'info', metadata = {}, phone, sendSms } = req.body;
    let userLang = req.body.language || req.body.preferredLanguage;

    // Check user's preferred language from MongoDB if not supplied directly
    if (!userLang && userId) {
      try {
        const user = await User.findById(userId).select('preferredLanguage language phone');
        if (user) {
          userLang = user.preferredLanguage || user.language || 'en';
        }
      } catch (userErr) {
        logger.warn(`Could not resolve user preferred language: ${userErr.message}`);
      }
    }
    userLang = userLang || 'en';

    let finalMessage = message;
    const isHighRiskAlert =
      type === 'alert' ||
      metadata.riskLevel === 'high' ||
      metadata.severity === 'critical' ||
      req.body.isHighRisk;

    // Translate High-Risk alerts into user's preferred language
    if (isHighRiskAlert && userLang !== 'en') {
      finalMessage = await translateText(message, 'en', userLang);
      logger.info(
        `[Bhashini] High-Risk alert translated to '${userLang}': "${message}" -> "${finalMessage}"`
      );
    }

    // Save to MongoDB with translated payload
    const notification = await Notification.create({
      userId,
      message: finalMessage,
      type,
      metadata: {
        ...metadata,
        originalMessage: message,
        language: userLang,
        isHighRisk: isHighRiskAlert,
        bhashiniTranslated: userLang !== 'en',
      },
    });

    // SMS dispatch simulation for remote / low-network areas
    const targetPhone = phone || req.body.phone;
    if (sendSms || targetPhone) {
      logger.info(
        `[SMS Dispatch - Remote/Low Network] Sent SMS to ${targetPhone || 'Assigned Driver'} in [${userLang.toUpperCase()}]: "${finalMessage}"`
      );
    }

    // Emit live event via Socket.io if available
    const io = req.app.get('io');
    if (io) {
      io.emit('notification_received', {
        notification,
        language: userLang,
        message: finalMessage,
      });
    }

    return apiResponse.success(
      res,
      201,
      'Notification created and translated successfully',
      notification
    );
  } catch (err) {
    logger.error(`Failed to create notification: ${err.message}`);
    return apiResponse.error(
      res,
      500,
      'Failed to create notification',
      err.message
    );
  }
});

/**
 * GET /api/notifications/:userId
 * Fetch all notifications for the specified user
 */
router.get('/:userId', async (req, res) => {
  try {
    const { userId } = req.params;
    const notifications = await Notification.find({ userId })
      .sort({ createdAt: -1 })
      .populate('userId', 'name email preferredLanguage');

    return apiResponse.success(
      res,
      200,
      'User notifications fetched successfully',
      notifications
    );
  } catch (err) {
    return apiResponse.error(
      res,
      500,
      'Failed to fetch notifications',
      err.message
    );
  }
});

module.exports = router;
